GET https://localhost:6001?culture=nothing
custom-header: DistDevRequest
Authorization: Bearer {JWT Token}

###

POST https://localhost:6001/api/cache/v1?culture=en
Content-Type: application/json
custom-header: DistDevRequest
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEwNGZkMWNjLTZjODQtNGM0NC04ZTVjLTkxNzc4MzEzYjA1ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im1pbGFkQGh1bWJlci5jYSIsIlByb3ZpbmNlIjoiT04iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiVGVhY2hlciIsIk1hbmFnZXIiXSwibmJmIjoxNjMxODM3OTM1LCJleHAiOjE2NjMzNzM5MzUsImlzcyI6IkRpc3RyaWJ1dGVkIERldiBPcmdhbml6YXRpb24iLCJhdWQiOiJ3d3cuaHVtYmVyLmNhIn0.gIC1CDOZbpXKaZvQha-cypNAre8qB6PEd-cg3zbZhqk

{
    "key": "mykey2",
    "value": "my value 2"
}

###

GET https://localhost:6001/api/cache/v1/mykey2?culture=en
custom-header: DistDevRequest
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEwNGZkMWNjLTZjODQtNGM0NC04ZTVjLTkxNzc4MzEzYjA1ZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im1pbGFkQGh1bWJlci5jYSIsIlByb3ZpbmNlIjoiT04iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOlsiVGVhY2hlciIsIk1hbmFnZXIiXSwibmJmIjoxNjMxODM3OTM1LCJleHAiOjE2NjMzNzM5MzUsImlzcyI6IkRpc3RyaWJ1dGVkIERldiBPcmdhbml6YXRpb24iLCJhdWQiOiJ3d3cuaHVtYmVyLmNhIn0.gIC1CDOZbpXKaZvQha-cypNAre8qB6PEd-cg3zbZhqk

###

PUT https://localhost:6001/api/cache/v1
Content-Type: application/json
custom-header: DistDevRequest

{
    "key": "mykey1",
    "value": "my updated value 1"
}

###

DELETE https://localhost:6001/api/cache/v1/mykey1
custom-header: DistDevRequest
