GET https://localhost:6001?culture=nothing
custom-header: DistDevRequest
Authorization: Bearer {JWT Token}

###

POST https://localhost:6001/api/cache/v1?culture=en
Content-Type: application/json
custom-header: DistDevRequest
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJEaXN0cmlidXRlZCBEZXYgT3JnYW5pemF0aW9uIiwiaWF0IjoxNjMxNTYwNzg1LCJleHAiOjE2MzE3NDc1NDksImF1ZCI6Ind3dy5odW1iZXIuY2EiLCJzdWIiOiJtaWxhZC5naGFmb29yaUBodW1iZXIuY2EiLCJHaXZlbk5hbWUiOiJNaWxhZCIsIlN1cm5hbWUiOiJHaGFmb29yaSIsIkVtYWlsIjoibWlsYWQuZ2hhZm9vcmlAaHVtYmVyLmNhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkNvdXJzZSBDb29yZGluYXRvciIsIk1hbmFnZXIiLCJUZWFjaGVyIl19.cPIGqAwOuHaEPt6xLsIvIIllq1gH69KYjQ-tKcuSHL8


{
    "key": "mykey2",
    "value": "my value 2"
}

###

GET https://localhost:6001/api/cache/v1/mykey2?culture=en
custom-header: DistDevRequest
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJEaXN0cmlidXRlZCBEZXYgT3JnYW5pemF0aW9uIiwiaWF0IjoxNjMxNTYwNzg1LCJleHAiOjE2MzE3NDc1NDksImF1ZCI6Ind3dy5odW1iZXIuY2EiLCJzdWIiOiJtaWxhZC5naGFmb29yaUBodW1iZXIuY2EiLCJHaXZlbk5hbWUiOiJNaWxhZCIsIlN1cm5hbWUiOiJHaGFmb29yaSIsIkVtYWlsIjoibWlsYWQuZ2hhZm9vcmlAaHVtYmVyLmNhIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbIkNvdXJzZSBDb29yZGluYXRvciIsIk1hbmFnZXIiLCJUZWFjaGVyIl0sIlByb3ZpbmNlIjoiT04ifQ.AKaxiZwfBIj9GaNclVXuP5dcJg_rT8MpjTuknBSYIyA

###

PUT https://localhost:6001/api/cache/v1
Content-Type: application/json
custom-header: DistDevRequest

{
    "key": "mykey1",
    "value": "my updated value 1"
}

###

DELETE https://localhost:6001/api/cache/v1/mykey1
custom-header: DistDevRequest
