GET https://localhost:6001?culture=nothing
custom-header: DistDevRequest

###

POST https://localhost:6001/api/cache/v1?culture=en-CA
Content-Type: application/json
custom-header: DistDevRequest

{
    "key": "mykey1",
    "value": "my value 1"
}

###

GET https://localhost:6001/api/cache/v1/mykey1
custom-header: DistDevRequest

###

PUT https://localhost:6001/api/cache/v1
Content-Type: application/json
custom-header: DistDevRequest

{
    "key": "mykey1",
    "value": "my updated value 1"
}

###

DELETE https://localhost:6001/api/cache/v1/mykey1
custom-header: DistDevRequest
